[package]
name = "synchronize_backup"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
camino = "1"
clap = { version = "4", features = ["derive"] }
regex = { version = "1", default-features = false, features = ["std", "perf"] }
time = { version = "0.3", features = ["formatting", "local-offset", "macros"] }

[dev-dependencies]
assert_fs = "1"
test_helper = { path = "../test_helper" }
