[package]
name = "synchronize_backup"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
camino = "1.1.1"
clap = { version = "4.0.32", features = ["derive"] }
regex = "1.7.0"
time = { version = "0.3.17", features = ["formatting", "local-offset", "macros"] }

[dev-dependencies]
temporary_directory = { path = "../temporary_directory" }
