[package]
name = "synchronize_backup"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
camino = "1.1.3"
clap = { version = "4.1.8", features = ["derive"] }
regex = "1.7.1"
time = { version = "0.3.20", features = ["formatting", "local-offset", "macros"] }

[dev-dependencies]
assert_fs = "1.0.10"
test_helper = { path = "../test_helper" }
