[package]
name = "test_helper"
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = "1"

[lib]
doctest = false
test = false

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
missing_errors_doc = "allow"
nursery = "warn"
pedantic = "warn"
