[package]
name = "common"
edition.workspace = true
rust-version.workspace = true

[lib]
path = "lib.rs"

[dependencies]
anyhow = "1"
time = { version = "0.3", features = ["local-offset"] }
uniquote = "4"

[lints]
workspace = true
