[package]
name = "common"
edition.workspace = true
rust-version.workspace = true

[lib]
path = "lib.rs"

[dependencies]
anyhow = "1"
serde_json = "1"
time = { version = "0.3", features = ["local-offset"] }

[lints]
workspace = true
