[workspace]
members = [
    "assert_fs",
    "backup",
    "ninja_bootstrap",
    "synchronize_backup",
    "synchronize_partially",
    "test_helper",
]
resolver = "2"

[profile.dev]
debug = false

[profile.release]
strip = true
