[project]
name = "bin_from_ninja"
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "linux-ppc64le", "osx-64", "osx-arm64"]

[tasks]
all = "make all"
check = "make check"
example = "make example.ninja"
fmt = "make fmt"

[dependencies]
make = "4.4.1.*"
ninja = "1.13.0.*"
