[project]
name = "bin_from_ninja"
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "linux-ppc64le", "osx-64", "osx-arm64"]

[tasks]
all = "make all"
check = "make check"
example = "make example.ninja"
fmt = "make fmt"

# Remark: The dependencies could include "rust", but https://anaconda.org/conda-forge/rust is
# updated later than https://hub.docker.com/_/rust/
[dependencies]
jq = "1.7.1"
make = "4.4.1"
ninja = "1.12.1"
