[package]
name = "assert_fs"
edition = "2021"
description = "Local subset of the assert_fs crate from crates.io"

[dependencies]
tempfile = "3"

[lib]
doctest = false
test = false

[lints.rust]
dead_code = "allow"
