[package]
name = "structured_concurrency"
edition = "2021"

[profile.dev]
debug = false

[profile.release]
strip = true

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
nursery = "warn"
pedantic = "warn"
