[package]
name = "backup"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
clap = { version = "4.1.1", features = ["derive"] }
time = { version = "0.3.17", features = ["formatting", "local-offset", "macros"] }

[dev-dependencies]
temporary_directory = { path = "../temporary_directory" }
