[package]
name = "common"
edition.workspace = true
rust-version.workspace = true

[lib]
path = "lib.rs"
doctest = false
test = false

[dependencies]
anyhow = "1"
serde_json = "1"

[lints]
workspace = true
