[package]
name = "synchronize_partially"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
camino = "1.1.3"
clap = { version = "4.1.6", features = ["derive"] }

[dev-dependencies]
assert_fs = "1.0.10"
test_helper = { path = "../test_helper" }
