[package]
name = "synchronize_partially"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
camino = "1"
clap = { version = "4", features = ["derive"] }

[dev-dependencies]
assert_fs = "1"
test_helper = { path = "../test_helper" }
